///////////////////////////////////////////////////////////
//  Berserk.cs
//  Implementation of the Class Berserk
//  Generated by Enterprise Architect
//  Created on:      20-Oct-2017 8:38:13 AM
//  Original author: Dylan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public class Berserk :  Warrior {

		public int currentHealth;
		private bool missTurn;

		public Berserk(bool missturn, int chp)
        {
            missTurn = missturn;
            currentHealth = chp;
		}

		~Berserk(){

		}

		public double calcSpecialAttack()
        {
            throw new NotImplementedException();

        }

		public int getSpecialAttackDamage(){

            throw new NotImplementedException();
        }

		public void specialAttackFailure(){
            throw new NotImplementedException();
        }

	}//end Berserk

}//end namespace Class