///////////////////////////////////////////////////////////
//  Fireball.cs
//  Implementation of the Class Fireball
//  Generated by Enterprise Architect
//  Created on:      20-Oct-2017 8:38:13 AM
//  Original author: Dylan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public class Fireball : SpecialAttack, Mage {

		public int currentHealthPoints;

		public Fireball(){

		}

		~Fireball(){

		}

		public double calcSpecialAttack(){

            throw new NotImplementedException(); 
		}

		private int damageSelf(){

            throw new NotImplementedException();
        }

		public int getSpecialAttackDamage(){

            throw new NotImplementedException();
        }

		public void specialAttackFailure(){
            throw new NotImplementedException();
        }

	}//end Fireball

}//end namespace Class