///////////////////////////////////////////////////////////
//  GameController.cs
//  Implementation of the Class GameController
//  Generated by Enterprise Architect
//  Created on:      20-Oct-2017 8:38:13 AM
//  Original author: Dylan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Class;


namespace Class {
	public class GameController {

		public string Class;
		private NonPlayerCharacter enemy;
		private PlayerCharacter player;
		public PlayerCharacter m_PlayerCharacter;
		public NonPlayerCharacter m_NonPlayerCharacter;

        public void startBattle()
        {
            throw new NotImplementedException();
        }

        public GameController(PlayerCharacter playerCharacter, NonPlayerCharacter nonPlayerCharacter, NonPlayerCharacter m_npc, PlayerCharacter m_pc)
        {
            playerCharacter = player;
            nonPlayerCharacter = enemy;
            m_PlayerCharacter = m_pc;
            m_NonPlayerCharacter = m_npc;
        }

        public object normalAttack()
        {
            throw new NotImplementedException();
        }

        public object specialAttack()
        {
            throw new NotImplementedException();
        }

        public string ChoosePlayerClass(string v)
        {
            throw new NotImplementedException();
        }
    }

		public string ChoosePlayer()
        {
        throw new NotImplementedException();
                return "";
		}

		public void startBattle()
        {

		}

	}//end GameController

}//end namespace Class