///////////////////////////////////////////////////////////
//  NormalAttack.cs
//  Implementation of the Class NormalAttack
//  Generated by Enterprise Architect
//  Created on:      20-Oct-2017 8:38:13 AM
//  Original author: Dylan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public abstract class NormalAttack
    {



		public NormalAttack()
        {

		}

		

		}

		private int getNormalAttackDamage(){

        throw new NotImplementedException();
       
		}

		public int takeDamage(){

        throw new NotImplementedException();
    }

	}//end NormalAttack

}//end namespace Class