///////////////////////////////////////////////////////////
//  Thief.cs
//  Implementation of the Class Thief
//  Generated by Enterprise Architect
//  Created on:      20-Oct-2017 8:38:13 AM
//  Original author: Dylan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public class Thief : PlayerCharacter {

		public Thief()
        {
            
		}

		}

		private void SpecialAttack()
        {

		}

	}//end Thief

}//end namespace Class